language: java
jdk:
- openjdk7
install:
- ./build-omny.sh
script:
- ./build-travis.sh
- ./bundle.sh $TRAVIS_BUILD_NUMBER
deploy:
  provider: s3
  access_key_id: AKIAJPII7N6DVIOXPQAQ
  secret_access_key:
    secure: iBGd+USVrrMzZdBh3jTp4GCEL7E4gKkd56Gkhsz2AUgal6gMROBmi3f6q9Vcr3ogM33WVRkjN63LKfVocdj5iTYAt64cgTwPNoPbCu0VTRVK4DKYScRbSRiN2YgUrGiiKCHqB0J/7aw8LGunF691s5fOAeVUm6XIhY2gT+9j5XA=
  bucket: omny-ecs-releases
  skip_cleanup: true
  local-dir: output
  on:
    repo: omnycms/omny-ecs
